version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - COMPOSE_CONVERT_WINDOWS_PATHS
    restart: always
    ports:
      - 3306:3306
  modx:
    build: ./php
    volumes:
      - ./data/html:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports:
      - 80:80
    links:
      - modx
